CREATE TABLE IF NOT EXISTS USERS
(
    ID    BIGINT generated by default as identity primary key,
    NAME  VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL,
    CONSTRAINT un_email UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ID          BIGINT generated by default as identity primary key,
    NAME        VARCHAR(64) NOT NULL,
    DESCRIPTION VARCHAR(64) NOT NULL,
    AVAILABLE   BOOLEAN     NOT NULL,
    OWNER_ID    BIGINT,
    REQUEST_ID  BIGINT,
    CONSTRAINT fk_user
        FOREIGN KEY (owner_id)
            REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS BOOKINGS
(
    ID          BIGINT generated by default as identity primary key,
    START_TIME  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FINISH_TIME TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ITEM_ID     BIGINT,
    BOOKER_ID   BIGINT,
    STATUS      VARCHAR(15),
    CONSTRAINT fk_item
        FOREIGN KEY (item_id)
            REFERENCES items (id),
    CONSTRAINT fk_booker
        FOREIGN KEY (booker_id)
            REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID        BIGINT generated by default as identity primary key,
    TEXT      VARCHAR(240)                NOT NULL,
    ITEM_ID   BIGINT                      NOT NULL,
    AUTHOR_ID BIGINT                      NOT NULL,
    CREATED   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_item_comment
        FOREIGN KEY (item_id)
            REFERENCES items (id),
    CONSTRAINT fk_author
        FOREIGN KEY (author_id)
            REFERENCES users (id)
);



